secretsprovider: gcpkms://projects/exvs2ib-analyzer/locations/asia-northeast1/keyRings/pulumi-secrets/cryptoKeys/pulumi-state
encryptedkey: CiQAll9D5d1UfBgQCPwxIK7lhY2Nmj9h8+QoNlRNXZtG6hZ2ENgSSADTCZ+A4ORiOrqJM/CSYXSXcH2H9xpwwL5MsJbPD9yXTantitJt/o+fSKysqZ/lVXjn6tyI+Jj19I4AL5/1ioU2U1v7QvQWEg==
config:
  exvs-app:cpu: "2"
  exvs-app:domain: www.exvs-analyzer.com
  exvs-app:firestoreDatabase: exvs-analyzer
  exvs-app:image:
    secure: v1:UqTnL38ot0pEuU0+:wjJutyc/8CjQqz1Wf/WFERTyoJa3Oi1U/5mFpwR3DG2gw/8poEFV4HHWvJYwDYkATEiUyrYsmQvhmlJP3P7Rhs/dwr5yaXoppAwhBvwleHBdkmVMyucgUeKGIzfmMzX1sZIyw7TpEBxtEbFT/spdKGBlJ9S9WQ==
  exvs-app:maxInstances: "3"
  exvs-app:memory: 1Gi
  exvs-app:serviceName: exvs-analyzer
  exvs-app:sharedStack: organization/exvs-shared/shared
  gcp:project: exvs2ib-analyzer
  gcp:region: asia-northeast1
  exvs-app:sessionEncryptionKey:
    secure: v1:ay3DXBLUnNZxg2tO:rv3t+K6ITd6nu3MXxCOo0Y5f4tlBSRVAlSJEe2Tj2PxDN0Cm7D6CgI0IvGAcFqQPPz1MpoM/K8JAKmoeMdK75/waKpfrTQiWtFGKgBNnnZ0=
