secretsprovider: gcpkms://projects/exvs2ib-analyzer/locations/asia-northeast1/keyRings/pulumi-secrets/cryptoKeys/pulumi-state
encryptedkey: CiQAll9D5WDA7usIHCU/rNrKnSr+O2Xzg+vXaTCsa5NSOw6loLISSQDTCZ+A4B7OnFsieoFe5+hdATGg6IDYWfj2OxYlVBH4gDymLO8WhUw5UYJ5YlZsazRt77LU3cBiJL+jnrYBIl1IdyxBbkqVgkU=
config:
  exvs-app:cpu: "1"
  exvs-app:domain: stg.exvs-analyzer.com
  exvs-app:firestoreDatabase: exvs-analyzer
  exvs-app:image:
    secure: v1:dXC5R4f6q31Rj2//:WIrHCkI7UnE5WcbnfXGJ3ApdXpt7H/VKxTz6cdodGxCqvqyXcJRzUak4VJFx62Tn3BYdfXtZsVBZr12a9F3y0ndLh7pHOxEJ74SUofnUKjt3BuSQY5raInTKsRJCZ4X04M6XHrrJ359g8fbyGoxbA7vJOw69FQ==
  exvs-app:maxInstances: "1"
  exvs-app:memory: 512Mi
  exvs-app:serviceName: stg-exvs-analyzer
  exvs-app:sharedStack: organization/exvs-shared/shared
  gcp:project: exvs2ib-analyzer
  gcp:region: asia-northeast1
  exvs-app:sessionEncryptionKey:
    secure: v1:vVvFyaTGB6LXa+TX:E27DnnLeNESxIaq6IFlX4gi796mnG+zlD4OexyrgqOsIo35FLA09sGjwV1DNUwiczGdx3IbF5Qidmm2P8kPJYrudDDJ3rOMj4fmJ5dOjgY4=
